### ISSUE TITLE
Literally doesn't work

### ISSUE THREAD

**Issue by iiDk-the-actual** [Nuzair46/Lyrixed#1]
![image](https://github.com/Nuzair46/Lyrixed/assets/54154105/22d94133-45f1-4127-b95f-06493949e420)
https://genius.com/Fifth-harmony-worth-it-lyrics

**Comment by iiDk-the-actual** [comment]
nvm just unstable

**Comment by Nuzair46** [comment]
try this
In the file you downloaded, you can go to
> index.js
> Open it in nodepad 
> go here and get an api key https://cors.sh/
> in the notepad, find `temp_e7329afcb73a45e7477057d88af764c1` and replace with the key you got.
> save it and run spicetify apply.
> 
> this should work.
> 
>  If you still get issue, go here https://genius.com/api-clients create account and create a client and copy the client secret. and in the index.js replace 
> `22jcx1liqiOP9FTUEly8UIRnpD-kAr0Vmvq8GQ8xzyDahhM2IkkGbCgM1TccbAKx` with your key.
> save and spicetify apply

**Comment by Become-ILLUSORY** [comment]
> try this In the file you downloaded, you can go to
> 
> > index.js
> > Open it in nodepad
> > go here and get an api key https://cors.sh/
> > in the notepad, find `temp_e7329afcb73a45e7477057d88af764c1` and replace with the key you got.
> > save it and run spicetify apply.
> > this should work.
> > If you still get issue, go here https://genius.com/api-clients create account and create a client and copy the client secret. and in the index.js replace
> > `22jcx1liqiOP9FTUEly8UIRnpD-kAr0Vmvq8GQ8xzyDahhM2IkkGbCgM1TccbAKx` with your key.
> > save and spicetify apply

But I get ''Since this key is a temporary key to get you started, you have to sign-in & claim your account to get a permanent one. This key will only be valid for 3 days.''

This way is only for three days？

**Comment by Nuzair46** [comment]
You can create an account to get a free key for more use
