### ISSUE TITLE
Why use https://genius.com/api/search/song instead of http://api.genius.com/search

### ISSUE THREAD

**Issue by giveup** [Nuzair46/Lyrixed#13]
Some lyrics can be found using `http://api.genius.com/search` but cannot be found with `https://genius.com/api/search/song`.
For example `ライトダンス`.

**Comment by Nuzair46** [comment]
If I use api.genius.com, it gets a little complicated as you will need the genius api key and if I use my key, it will get ratelimitted.
Regarding support for Japanese/Romaji lyrics, Im thinking of adding other lyrics providers. But currently i lack the time to do. So please wait 👍🏼
