### ISSUE TITLE
how do i unistall

### ISSUE THREAD

**Issue by mezo7272** [Nuzair46/Lyrixed#2]
i deleted the lyrixed folder from custoum apps but it still shows on spotify
![image](https://github.com/Nuzair46/Lyrixed/assets/79715642/f3150960-15fe-42fe-b177-47e4e73a771f)
![image](https://github.com/Nuzair46/Lyrixed/assets/79715642/656edd7d-0c22-4fbd-987c-e8dd46dd4864)

**Comment by throwaway2041** [comment]
you do 

```
spicetify config custom_apps lyrixed
spicetify apply
```
in Powershell or whatever you use

**Comment by Nuzair46** [comment]
added to readme
