### ISSUE TITLE
Lyrics error

### ISSUE THREAD

**Issue by kevinbaba95** [Nuzair46/Lyrixed#4]
Lyrics error 'Coudent find lyrics for this one' on every song
![Screenshot 2024-05-22 155209](https://github.com/Nuzair46/Lyrixed/assets/108137165/5fafb28d-d2e2-4a5a-a4a0-9270e56d05b9)

**Comment by moon250** [comment]
Same here ...
Even tried with the song in the preview.png 😅
![image](https://github.com/Nuzair46/Lyrixed/assets/60036441/fbbcaf58-15ba-4f27-a189-987a7c1d2d42)

**Comment by moon250** [comment]
After a quick look in the console, it seems we just are being rate-limited
![image](https://github.com/Nuzair46/Lyrixed/assets/60036441/f07e6f26-1883-47e8-a0d1-72090b0b9ac1)

**Comment by RobotFK** [comment]
I think this could be fixed by [Cors accepting this software (via a Github issue) as OSS](github.com/gridaco/cors.sh/issues/76) and the new key then being implemented.

**Comment by Nuzair46** [comment]
I can fix it another way. I just didnt get time to do it. i will fix it next release

**Comment by LordEnder-Kitty** [comment]
so, this is getting fixed? nice. i just found spicetify for the soul purpose of getting lyrics back. if this works, imma be very happy.

**Comment by Nuzair46** [comment]
Fixed with latest release https://github.com/Nuzair46/Lyrixed/releases/tag/2.0.0
