### ISSUE TITLE
any chance for using Musixmatch as lyric source just like eeveespotify?

### ISSUE THREAD

**Issue by ElliotCHEN37** [Nuzair46/Lyrixed#6]
any chance for using Musixmatch as lyric source just like eeveespotify?

**Comment by dtzdev** [comment]
Would be pretty hard cause the Musixmatch API access is limited to Musixmatch selected partners.

**Comment by Nuzair46** [comment]
I could do it. but i need time

**Comment by dtzdev** [comment]
I think apple music has an api for lyrics. The source is musixmatch. Maybe that could be used, idk.
