### ISSUE TITLE
Couldn't find lyrics for this one. 

### ISSUE THREAD

**Issue by Laiment1** [Nuzair46/Lyrixed#8]
![Screenshot 2024-06-14 115116](https://github.com/Nuzair46/Lyrixed/assets/172749328/888dc25e-e41f-42da-a870-18a247a37acc)

**Comment by Banchion007** [comment]
also having this issue

**Comment by Laiment1** [comment]
> also having this issue

Did you find a solve?

**Comment by Nuzair46** [comment]
Try this

In the file you downloaded, you can go to
index.js
Open it in nodepad 
go here and get an api key https://cors.sh/
in the notepad, find temp_e7329afcb73a45e7477057d88af764c1 and replace with the key you got.
save it and run spicetify apply.

this should work.

 If you still get issue, go here https://genius.com/api-clients create account and create a client and copy the client secret. and in the index.js replace 
22jcx1liqiOP9FTUEly8UIRnpD-kAr0Vmvq8GQ8xzyDahhM2IkkGbCgM1TccbAKx with your key.
save and spicetify apply

If this doesn't work, wait for the weekend, i will try to fix another way.

**Comment by Nuzair46** [comment]
closing as its same as #4

**Comment by Banchion007** [comment]
I did as you reccomended, and had no success. I hope you find a solution soon!

**Comment by Nuzair46** [comment]
Reinstall. Its fixed now
